spring:
# redis配置，以下有默认配置的也可以使用默认配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空，如果redis服务端配置文件开启了requirepass 密码，此处就应该填写相应的配置密码）
    password: 
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制，对应maxTotal）
      max-active: 8
      # 连接池中的最大空闲连接
      max-wait: 1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0   
            
# 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
myFile:
  basePath: E:\test
  url: 
