spring:
  #mybits配置
  datasource:
     url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     platform: mysql
     type: com.alibaba.druid.pool.DruidDataSource
     #下面为连接池的补充设置，应用到上面所有数据源中 
     # 初始化大小，最小，最大
     initial-size: 10
     dbcp2:
      min-idle: 10 
      max-idle: 200
  #redis配置，以下有默认配置的也可以使用默认配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空，如果redis服务端配置文件开启了requirepass 密码，此处就应该填写相应的配置密码）
    password: 
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制，对应maxTotal）
      max-active: 8
      # 连接池中的最大空闲连接
      max-wait: 1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0               
  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB

#mybatis配置
mybatis:
  #实体类所做包
  type-aliases-package: com.example.demo.model
  #mapper.xml所在位置
  mapperLocations: classpath:mapper/*.xml

logging:
    level:
      com.example.demo.mapper: DEBUG 


